/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUnitsIndexRouteImport } from './routes/_layout/units/index'
import { Route as LayoutStaffIndexRouteImport } from './routes/_layout/staff/index'
import { Route as LayoutResidentsIndexRouteImport } from './routes/_layout/residents/index'
import { Route as LayoutReportsIndexRouteImport } from './routes/_layout/reports/index'
import { Route as LayoutMaintenanceIndexRouteImport } from './routes/_layout/maintenance/index'
import { Route as LayoutGateIndexRouteImport } from './routes/_layout/gate/index'
import { Route as LayoutConversationsIndexRouteImport } from './routes/_layout/conversations/index'
import { Route as LayoutBillingIndexRouteImport } from './routes/_layout/billing/index'
import { Route as LayoutAnnouncementsIndexRouteImport } from './routes/_layout/announcements/index'
import { Route as LayoutAmenitiesIndexRouteImport } from './routes/_layout/amenities/index'
import { Route as LayoutAmenitiesBookingsIndexRouteImport } from './routes/_layout/amenities/bookings/index'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutUnitsIndexRoute = LayoutUnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutStaffIndexRoute = LayoutStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutResidentsIndexRoute = LayoutResidentsIndexRouteImport.update({
  id: '/residents/',
  path: '/residents/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutReportsIndexRoute = LayoutReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutMaintenanceIndexRoute = LayoutMaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutGateIndexRoute = LayoutGateIndexRouteImport.update({
  id: '/gate/',
  path: '/gate/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutConversationsIndexRoute =
  LayoutConversationsIndexRouteImport.update({
    id: '/conversations/',
    path: '/conversations/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutBillingIndexRoute = LayoutBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutAnnouncementsIndexRoute =
  LayoutAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutAmenitiesIndexRoute = LayoutAmenitiesIndexRouteImport.update({
  id: '/amenities/',
  path: '/amenities/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutAmenitiesBookingsIndexRoute =
  LayoutAmenitiesBookingsIndexRouteImport.update({
    id: '/amenities/bookings/',
    path: '/amenities/bookings/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/amenities/': typeof LayoutAmenitiesIndexRoute
  '/announcements/': typeof LayoutAnnouncementsIndexRoute
  '/billing/': typeof LayoutBillingIndexRoute
  '/conversations/': typeof LayoutConversationsIndexRoute
  '/gate/': typeof LayoutGateIndexRoute
  '/maintenance/': typeof LayoutMaintenanceIndexRoute
  '/reports/': typeof LayoutReportsIndexRoute
  '/residents/': typeof LayoutResidentsIndexRoute
  '/staff/': typeof LayoutStaffIndexRoute
  '/units/': typeof LayoutUnitsIndexRoute
  '/amenities/bookings/': typeof LayoutAmenitiesBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/amenities': typeof LayoutAmenitiesIndexRoute
  '/announcements': typeof LayoutAnnouncementsIndexRoute
  '/billing': typeof LayoutBillingIndexRoute
  '/conversations': typeof LayoutConversationsIndexRoute
  '/gate': typeof LayoutGateIndexRoute
  '/maintenance': typeof LayoutMaintenanceIndexRoute
  '/reports': typeof LayoutReportsIndexRoute
  '/residents': typeof LayoutResidentsIndexRoute
  '/staff': typeof LayoutStaffIndexRoute
  '/units': typeof LayoutUnitsIndexRoute
  '/amenities/bookings': typeof LayoutAmenitiesBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_layout/amenities/': typeof LayoutAmenitiesIndexRoute
  '/_layout/announcements/': typeof LayoutAnnouncementsIndexRoute
  '/_layout/billing/': typeof LayoutBillingIndexRoute
  '/_layout/conversations/': typeof LayoutConversationsIndexRoute
  '/_layout/gate/': typeof LayoutGateIndexRoute
  '/_layout/maintenance/': typeof LayoutMaintenanceIndexRoute
  '/_layout/reports/': typeof LayoutReportsIndexRoute
  '/_layout/residents/': typeof LayoutResidentsIndexRoute
  '/_layout/staff/': typeof LayoutStaffIndexRoute
  '/_layout/units/': typeof LayoutUnitsIndexRoute
  '/_layout/amenities/bookings/': typeof LayoutAmenitiesBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/amenities/'
    | '/announcements/'
    | '/billing/'
    | '/conversations/'
    | '/gate/'
    | '/maintenance/'
    | '/reports/'
    | '/residents/'
    | '/staff/'
    | '/units/'
    | '/amenities/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/amenities'
    | '/announcements'
    | '/billing'
    | '/conversations'
    | '/gate'
    | '/maintenance'
    | '/reports'
    | '/residents'
    | '/staff'
    | '/units'
    | '/amenities/bookings'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/login/'
    | '/_layout/amenities/'
    | '/_layout/announcements/'
    | '/_layout/billing/'
    | '/_layout/conversations/'
    | '/_layout/gate/'
    | '/_layout/maintenance/'
    | '/_layout/reports/'
    | '/_layout/residents/'
    | '/_layout/staff/'
    | '/_layout/units/'
    | '/_layout/amenities/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/units/': {
      id: '/_layout/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof LayoutUnitsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/staff/': {
      id: '/_layout/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof LayoutStaffIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/residents/': {
      id: '/_layout/residents/'
      path: '/residents'
      fullPath: '/residents/'
      preLoaderRoute: typeof LayoutResidentsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/reports/': {
      id: '/_layout/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof LayoutReportsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/maintenance/': {
      id: '/_layout/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof LayoutMaintenanceIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/gate/': {
      id: '/_layout/gate/'
      path: '/gate'
      fullPath: '/gate/'
      preLoaderRoute: typeof LayoutGateIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/conversations/': {
      id: '/_layout/conversations/'
      path: '/conversations'
      fullPath: '/conversations/'
      preLoaderRoute: typeof LayoutConversationsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/billing/': {
      id: '/_layout/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof LayoutBillingIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/announcements/': {
      id: '/_layout/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof LayoutAnnouncementsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/amenities/': {
      id: '/_layout/amenities/'
      path: '/amenities'
      fullPath: '/amenities/'
      preLoaderRoute: typeof LayoutAmenitiesIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/amenities/bookings/': {
      id: '/_layout/amenities/bookings/'
      path: '/amenities/bookings'
      fullPath: '/amenities/bookings/'
      preLoaderRoute: typeof LayoutAmenitiesBookingsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAmenitiesIndexRoute: typeof LayoutAmenitiesIndexRoute
  LayoutAnnouncementsIndexRoute: typeof LayoutAnnouncementsIndexRoute
  LayoutBillingIndexRoute: typeof LayoutBillingIndexRoute
  LayoutConversationsIndexRoute: typeof LayoutConversationsIndexRoute
  LayoutGateIndexRoute: typeof LayoutGateIndexRoute
  LayoutMaintenanceIndexRoute: typeof LayoutMaintenanceIndexRoute
  LayoutReportsIndexRoute: typeof LayoutReportsIndexRoute
  LayoutResidentsIndexRoute: typeof LayoutResidentsIndexRoute
  LayoutStaffIndexRoute: typeof LayoutStaffIndexRoute
  LayoutUnitsIndexRoute: typeof LayoutUnitsIndexRoute
  LayoutAmenitiesBookingsIndexRoute: typeof LayoutAmenitiesBookingsIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAmenitiesIndexRoute: LayoutAmenitiesIndexRoute,
  LayoutAnnouncementsIndexRoute: LayoutAnnouncementsIndexRoute,
  LayoutBillingIndexRoute: LayoutBillingIndexRoute,
  LayoutConversationsIndexRoute: LayoutConversationsIndexRoute,
  LayoutGateIndexRoute: LayoutGateIndexRoute,
  LayoutMaintenanceIndexRoute: LayoutMaintenanceIndexRoute,
  LayoutReportsIndexRoute: LayoutReportsIndexRoute,
  LayoutResidentsIndexRoute: LayoutResidentsIndexRoute,
  LayoutStaffIndexRoute: LayoutStaffIndexRoute,
  LayoutUnitsIndexRoute: LayoutUnitsIndexRoute,
  LayoutAmenitiesBookingsIndexRoute: LayoutAmenitiesBookingsIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
